services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
      - ./backend/db.sqlite3:/app/db.sqlite3
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - task_schedule_network

  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - task_schedule_network

volumes:
  static_volume:
  media_volume:

networks:
  task_schedule_network:
    driver: bridge