# Generated by Django 5.2.7 on 2026-04-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics'), ('MECH', 'Mechanical'), ('IT', 'Information Technology'), ('CSBS', 'Computer Science & Business Systems'), ('AIML', 'Artifical Intelligence and Machine Learning'), ('AIDS', 'Artifical Intelligence and Data Science'), ('CYS', 'CyberSecurity'), ('OFFICE', 'Kite Office'), ('MBA', 'Master of Business Administration'), ('INNOVATION TEAM', 'Innovation Team'), ('OTHERS', 'Non-Teaching Staffs'), ('PLACEMENT', 'Placement Department'), ('RA', 'Robotics & Automation'), ('S&H', 'Science & Humanities'), ('IQAC', 'IQAC')], max_length=50, null=True),
        ),
    ]
