# Generated by Django 5.2.7 on 2026-04-07 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_user_designation_alter_user_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='designation',
        ),
    ]
