# Generated by Django 5.2.6 on 2025-10-14 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hod_name', models.CharField(max_length=100)),
                ('hod_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('TASK_CREATOR', 'Task Creator'), ('TASK_ASSIGNER', 'Task Assigner'), ('STAFF', 'Staff')], default='STAFF', max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='task.department')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('assigned_on', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField()),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20)),
                ('assigned_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'TASK_ASSIGNER'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to='task.staff')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'STAFF'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks_to_do', to='task.staff')),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'TASK_CREATOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to='task.staff')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='task.department')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
