# Generated by Django 5.2.6 on 2025-10-14 07:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='department',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='staff.staff'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_by',
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-issued_on'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_on',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed_on',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_on',
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_modification_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_tasks', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='task',
            name='issued_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_tasks', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='task',
            name='last_edited_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='staff_hod',
            field=models.ForeignKey(limit_choices_to={'role': 'HOD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_tasks', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
