# Generated by Django 5.2.7 on 2025-10-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_completed_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_created_881111_idx',
            old_name='tasks_created_816ff3_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='reminder1',
            field=models.DateTimeField(blank=True, help_text='First reminder date and time', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder2',
            field=models.DateTimeField(blank=True, help_text='Second reminder date and time', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.CharField(help_text='Name of the person who requested this task', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
