# Generated by Django 5.2.6 on 2025-10-11 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_staff_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='updated_at',
        ),
    ]
