# Generated by Django 5.2.6 on 2025-10-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_staff_created_at_remove_staff_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('HOD', 'Head of Department')], default='STAFF', max_length=10),
        ),
    ]
