# Generated by Django 5.2.7 on 2025-10-14 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_staff_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
